<?php
 include_once("FY_fun.php");
 ZY();
 $H=new FY_html();
 if (SE('SU_id')==""){
 $H->ar("<script type='text/javascript' src='".F_HT."FY_img/jquery1.8.min.js'></script>");
 $H->ar("<script type='text/javascript' src='".F_HT."FY_img/log.js'></script>");
 $H->ar("<div id='login'>");
 $H->ar("  <div class='log'>");
 $H->ar("    <div class='logl'><img src='".F_HT."FY_img/log.png'></div>");
 $H->ar("    <form>");
 $H->ar("      <input type='text' name='us' maxlength='15' class='a'>");
 $H->ar("      <input name='pw' type='password' maxlength='15' class='a'>");
 $H->ar("      <input type='text' name='yz' class='b' maxlength='6'><span class='c'><img src='".F_ML."minuo/YZ.php' onClick=src='".F_ML."minuo/YZ.php?n='+Math.random(); onerror=this.onerror=null;this.src='".F_ML."minuo/YZ.php?n='+Math.random();/></span>");
 $H->ar("      <input type='button' class='d' value=' '>");
 $H->ar("      <input type='reset' class='e' value=' '>");
 $H->ar("    </form>");
 $H->ar("  </div>");
 $H->ar("</div>");
 }else{
 $H->ar("<script type='text/javascript' src='".F_HT."FY_img/lhgdialog.js'></script>");
 $H->ar("<script type='text/javascript' src='".F_HT."FY_img/FY.js'></script>");
 $H->ar("<script type='text/javascript' src='".F_HT."FY_img/table.js'></script>");
 $H->ar("<script type='text/javascript' src='".F_HT."FY_editor/kindeditor-min.js'></script>");
 $H->ar("<script type='text/javascript' src='".F_HT."FY_editor/lang/zh_CN.js'></script>");
 $H->ar("<script type='text/javascript' src='".F_HT."laydate/laydate.js'></script>");
 $H->ar("<script type='text/javascript' src='".F_HT."FY_editor/FY.js'></script>");
// $H->ar("<script type='text/javascript' src='".F_ML."FY_img/Validform.js'>< /script>");
 $H->ar("<link href='".F_HT."FY_img/FY.css' rel='stylesheet' type='text/css' />");
 $H->ar("<div id='web'>");
 $H->ar("  <div id='Top'>");
 $H->ar("    <a class='logo'></a>");
 $H->ar("    <div class='dh'>");
 $H->ar("      <li class='a'>网站首页</li>");
 $H->ar("      <li class='f'>安全退出</li>");
 $H->ar("    </div>");
 $H->ar("  </div>");
 $H->ar("  <div id='Left'>");
 $H->ar("    <li class='a w'><a class='b' dd=''>内容管理</a>");
 $H->ar("      <ul>");
 $H->ar("        <li><a dd='a_dy'>单页管理</a></li>");

 $H->ar("        <li><a dd='a_wd'>文档管理</a></li>");
 //$H->ar("        <li><a dd='a_wdl'>文档类型</a></li>");
 //$H->ar("        <li><a dd='a_cpt'>产品添加</a></li>");
 $H->ar("        <li><a dd='a_cp'>产品管理</a></li>");
 //$H->ar("        <li><a dd='a_cps'>产品批量</a></li>");
 // $H->ar("        <li><a dd='a_yslx'>运输路线</a></li>");
 // $H->ar("        <li><a dd='a_khjz'>客户见证</a></li>");
 $H->ar("        <li><a dd='a_adv'>广告管理</a></li>");
 $H->ar("        <li><a dd='a_sjdindan'>用户预约</a></li>");
 $H->ar("        <li><a dd='a_lj'>友情链接</a></li>");
 // $H->ar("        <li><a dd='a_hzhb'>合作伙伴</a></li>");
 $H->ar("        <li><a dd='a_bd'>百度商桥</a></li>");
 $H->ar("        <li><a dd='a_sy'>SEO</a></li>");
 // $H->ar("        <li><a dd='a_ly'>留言管理</a></li>");
 $H->ar("      </ul>");
 $H->ar("    </li>");
 $H->ar("    <li class='a c'><a class='b' dd=''>账户管理</a>");
 $H->ar("      <ul>");
 $H->ar("        <li><a dd='a_pwd'>密码管理</a></li>");
 //$H->ar("        <li><a dd=''>系统用户</a></li>");
 //$H->ar("        <li><a dd=''>文件管理</a></li>");
 //$H->ar("        <li><a dd=''>模板管理</a></li>");
 //$H->ar("        <li><a dd=''>水印管理</a></li>");
 $H->ar("      </ul>");
 $H->ar("    </li>");
 $H->ar("  </div>");
 $H->ar("  <div id='RT'><div class='twz'><span>当前位置：</span><span>内容管理</span><span>单页管理</span></div>");
 $H->ar("  </div>");
 $H->ar("  <div id='RTb' class='rt'>");
 $H->ar("  </div>");
 $H->ar("  <div id='Right'>");
 $H->ar("  </div>");
 $H->ar("  <div id='Bottom' class='rt'>");
 $H->ar("  </div>");
 $H->ar("</div>");
 $H->aj('$(function(){$("#Top .dh li.a").click(function(){window.open("/")})})');
 }
 echo $H->x();
?>